Asp.net,MVC/WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Know more about our company.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact us through the links";

            return View();
        }
    }
}

Asp.net,MVC/WebApplication1/WebApplication1/Controllers/ImageController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ImageController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(Image model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(model.ImageFile.FileName);
                    string imagePath = Path.Combine(Server.MapPath("~/Images/"), filename);
                    model.ImageFile.SaveAs(imagePath);

                    using (DbModels db = new DbModels())
                    {
                        model.ImagePath = "~/Images/" + filename;
                        db.Images.Add(model);
                        db.SaveChanges();
                    }

                    // Redirect to the "Index" action after successful upload
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = "Error uploading the image: " + ex.Message;
                }
            }

            return View(model);
        }




        public ActionResult Index()
        {
            using (DbModels db = new DbModels())
            {
                var images = db.Images.ToList();
                return View("view", images); 
            }
        }


        [HttpGet]
        public ActionResult View(int id)
        {
            using (DbModels db = new DbModels()) 
            {
                var model = db.Images.FirstOrDefault(x => x.ImageId == id);
                if (model != null)
                {
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
    }
}

Asp.net,MVC/WebApplication1/WebApplication1/Controllers/RegistrationController.cs
using System.Web.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly UserRepository userRepository;

        public RegistrationController()
        {
           
            string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            userRepository = new UserRepository(connectionString);
        }

        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel model, string action)
        {
            if (ModelState.IsValid)
            {
                switch (action)
                {
                    case "Insert":
                        userRepository.CreateUser(model);
                        ViewBag.Message = "Registration Successful!";
                        break;
                    case "View":
                        UserModel user = userRepository.GetUserByUsername(model.Username);
                        if (user != null)
                        {
                            return View("ViewUser", user);
                        }
                        else
                        {
                            ViewBag.Message = "User not found.";
                            break;
                        }

                    case "Delete":
                        userRepository.DeleteUserByUsername(model.Username);
                        ViewBag.Message = "User Deleted Successfully!";
                        break;
                    case "Update":
                        userRepository.UpdateUser(model);
                        ViewBag.Message = "User Information Updated!";
                        break;
                    default:
                        ViewBag.Message = "Invalid action.";
                        break;
                }
            }

            return View("Index", model);
        }
    }
}

Asp.net,MVC/WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Portfolio.</p>
</main>

Asp.net,MVC/WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        Portfolio<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        
    </address>
</main>

Asp.net,MVC/WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="imageInsertionTitle">
        <h2 id="imageInsertionTitle">Insert/View Images</h2>
        <p><a class="btn btn-outline-dark" href="@Url.Action("Add", "Image")">Click here &raquo;</a></p>
    </section>

    <section class="row" aria-labelledby="userRegistrationTitle">
        <h2 id="userRegistrationTitle">User Insert/View/Update/Delete</h2>
        <p><a class="btn btn-outline-dark" href="@Url.Action("Index", "Registration")">Click here &raquo;</a></p>
    </section>

</main>